<h2>SimplyBibTeX Help</h2>

<h3>About</h3>
SimplyBibTeX is a very simple but extremly flexible publishing system for BibTeX files. It allows to store manage, comment and link a bibliographic database.

<h3>Features</h3>
- BibTeX Parser
- XHTML Viewer (validating XHTML 1.0 and CSS)
- Feeds with autodetection
- RSS 2.0 Feeds per Database (validating)
- Atom Feeds per Database (validating for most databases)
- per item linking
- uploading in separate directory
- store meta data per database (comments, whatever you want)

<h3>Requirements</h3>
- PHP 4.x or 5.x

<h3>Installation</h3>
To be written!

<h3>Planned Features</h3>
- User managment
- Editing of databases
